### ISSUE TITLE
What's with the `on` prefix?

### ISSUE THREAD

**Issue by Hainesy** [TSOptics/optics#1]
This library looks very promising! Can you explain why you prefix all your optics with `on` in all the docs and examples? This confused me (and others) at first, suggesting it was a handler of some kind.

**Comment by auwtch** [comment]
Maybe it's about *focusing* **on** something.

**Comment by VincentQuillien** [comment]
Yes that's exactly it @blasterpistol .
Both event handlers and optics prefix their names with **on**, but for handlers it's followed by a verb (click, blur, select, submit, ...), while for optics it is followed by a noun (user, preferences, age, ...).

It is only a convention, you could name them something like `userOptic`, but it's important that the name carries this inflection to avoid having to put it on the name of the focused value.

```ts
const user = onUser.get();
// good

const userValue = user.get();
// ugly IMO
```

**Comment by Hainesy** [comment]
Not sure I fully understand the reasoning. Adding an `on` prefix to a handler makes sense because grammatically it reads like "on click do such and such". That doesn't really follow for nouns... "on user do something", does it?

**Comment by VincentQuillien** [comment]
For event handlers, just like you said it means "**on** event do something" while for optics it means "focused **on** something".
If it's followed by a noun you know it's the latter, if it's a verb you know it's the former.

I agree it is confusing since we have the same prefix but with a different meaning depending on if it's an optic or an event handler.
I don't have strong opinions on this naming convention, I'm open to suggestions.

**Comment by Siegrift** [comment]
Imho, the **on**Something convention is already well-settled for event handlers and the library should pick a different one. I'd personally use the suffix `Optic` like it was suggested above.

**Comment by VincentQuillien** [comment]
I've updated the docs to exclusively use the `Optic` suffix, it's a bit longer but more explicit !
