### ISSUE TITLE
Object prototype is not preserved on modification (and there is no option to activate this)

### ISSUE THREAD

**Issue by adrian-budau** [TSOptics/optics#19]
This could easily be solved like immer does with a special symbol that marks wether to use destructering or Object.create instead

**Comment by VincentQuillien** [comment]
Hello @adrian-budau 

Application state in general is supposed to only contain serializable values, because we need to be able to persist it, and we need it to correctly rehydrate on the client when using SSR.
That means prototypes are not expected to be preserved anyway, and we shouldn't rely on them for state management.

I get that there's still a need to associate behaviors to state, but such functions should live in the store/atom/optic and not inside the state itself.
In this respect I plan on supporting **actions**: custom state update functions that would be attached to the optic, letting us explicitly declare what operations are allowed for an optic.

Now for [DataOptic](https://www.optics.page/docs/Guides/data_optic/) there may be a case for preserving prototypes but I gotta be honest it's not high in my priority list.

**Comment by adrian-budau** [comment]
Ok, thanks, **actions** sound great when they do come. Thanks!

Should this issue be closed then?

**Comment by VincentQuillien** [comment]
Yes closing it. 👍
